### ISSUE TITLE
X/Y screen coordinates

### ISSUE THREAD

**Issue by DelanoLima** [bucanero/apollo-ps3#11]
When adjusting the vertical edge of the screen I get a black band at the bottom of the screen when the top edge reaches the top of the TV. Would you have to add X and Y position adjustment of the screen or leave the screen centered?

**Comment by bucanero** [comment]
the video library Tiny3D is a bit tricky because it uses virtual coordinates for positioning elements on the screen.

to adjust the image to each TV would require additional settings for the x,y offsets.  It's not a critical issue, and there's a lot of other features I want to complete first.
I might get back to it in a future version when I re-work the GUI.

**Comment by bucanero** [comment]
Fixed in 2395d9916751e1ac6df6015872136b7be0370553
