### ISSUE TITLE
[BLJM60064] Ryu ga Gotoku: Kenzan! couldn't be resigned

### ISSUE THREAD

**Issue by SandiHall1970** [bucanero/apollo-ps3#128]
I unencrypted my save using Apollo, transferred it to my PC, modified it using RPCS3 and Cheat Engine and transferred it back to my PS3 and tried to encrypt it.
When I go to resign my save, I get couldn't be resigned.
I can't find any info of the key on the conf file for Apollo or Bruteforce for PS3.

I can get the Secure File ID and disc hash key if needed.

**Comment by SandiHall1970** [comment]
Here's the key:

; "Ryu ga Gotoku: Kenzan!"
[BLJM60064]
;disc_hash_key=
secure_file_id:*=908AA7013F9B2D0088E1CB98159101D2

**Comment by bucanero** [comment]
It's not an issue on Apollo or a missing File key, you can't encrypt a save from RPCS3 because the emulator doesn't create some specific required PS3 files.

It's an issue on the emulator, they should implement PS3 saves properly and generate all files needed.

The only possible solution is to use an original PS3 save, and use the "Import decrypted data file" option on Apollo. Then you'll be injecting the decrypted data file in a proper PS3 save.
