### ISSUE TITLE
Resigned RPCS3 savedata is not loadable

### ISSUE THREAD

**Issue by m4st3rP** [bucanero/apollo-ps3#28]
I copied and resigned a savedata of Metal Gear Solid Peace Walker HD Edition that I have from playing the game in RPCS3 with Apollo Save Tool v1.4.2 but when I try to load it I get the error code 80120003. The savedata works in RPCS3.

These were my exact steps:
Copied the savadata from RPCS3 to the correct folder in a USB drive
Plugged the usb drive into my PS3 and started Apollo
Copied the savedata from my USB drive to the PS3 HDD
Selected "Apply Changes & Resign" on the copied HDD savedata
Started the game and upon loading the savedata getting the error code "80120003"

The savedata:
[NPED00686GAME001.zip](https://github.com/bucanero/apollo-ps3/files/5542924/NPED00686GAME001.zip)

**Comment by bucanero** [comment]
The problem lies in the RPCS3 domain: 
the emulator doesn't create proper PS3 saves because they just store the data without encryption. Most ps3 games encrypt their savegame data, but the emulator has not implemented the encryption/decryption layer at all.
The emulator even miss to create some required PS3 files like `PARAM.PFD`

So before even trying to resign it with Apollo, the data needs to be encrypted back as per the original format and key for that game. A computer tool such as `pfdtool` (linux, mac, win) or Bruteforce Savedata (Windows) could be used to regenerate and encrypt the savegame using a real PS3 save as template. I assume there might be guides online about it.

You can compare with a real PS3 savegame, for example here:
https://metalgearsolidinternationalpage.weebly.com/savegames.html

a real `NPED00686` savegame has a `PARAM.PFD` file, and the `00000000.000` data size is different:
- unencrypted: 314088 bytes
- encrypted: 314096 bytes

**Comment by m4st3rP** [comment]
All right. Sorry for asuming this was an issue with Apollo and thank you for the advice.
