### ISSUE TITLE
load .savepatch files from an external USB

### ISSUE THREAD

**Issue by ghost** [bucanero/apollo-ps3#67]
If not, it might be a cool feature in the future, as you could easily test an alternative patch file without FTPing it to your console and/or replacing and existing one. And, it might make it easier to distribute patches in the future (if the app ever stops updating its database of patch files).

**Comment by rhynec** [comment]
About this issue, I though of an easy way to implement the feature without heavily modifying program behavior or the GUI. Instead of allowing Apollo to read patches from both internal hard drive and USB (which would require labeling patch files by their source folder, and dealing with patch files for a game existing in both internal and USB), a toggle could be added to the settings menu which would switch Apollo from reading from internal to reading from external USB (I was thinking the path USBxxx/PS3/PATCHES/ might work). Though, dealing with multiple USB slots might be a bit problematic...

And as for patch files themselves, what if they were distributed separate from Apollo? So anytime you or anyone else wanted to update a cheat file, a new "ps3savepatch" pkg could be generated without having to wait for a new version of Apollo to come out (kind of how Aldo handles the PS2CONFIG pkg; I assume GitHub actions could be set up to regenerate the ps3savepatch pkg any time a new commit changes anything in the ps3patch folder). This if more for convenience's sake, having Apollo stand on its own even if someday new versions stop coming out (otherwise, default Apollo pkgs could come with outdated ps3savepatch files at any given time).

**Comment by bucanero** [comment]
I understand the feature (loading `*.ps3savepatch` from USB) and it could be added, but I honestly don't see it as a high priority... Apollo has been published for quite some time, and I have never received a single patch code update from anyone.

All this time I have updated the code list myself, whenever I found something from the Bruteforce savedata forum, but I think that nobody is actually doing any new codes.

Btw, Apollo has a "database update" feature (under "Settings") that downloads an updated appdata.zip file, and unpacks it. That was meant to cover the case when no more versions are released, but you could still keep the code list updated with new stuff. (I did the same for Artemis)
