### ISSUE TITLE
Black screen on rebug 4.41 dex

### ISSUE THREAD

**Issue by dfgdgdgfd** [bucanero/apollo-ps3#81]
I noticed another user reporting this, I started with the latest version.  It got up to installing the db files then black screen, with music.  Thought something was wrong with my hdmi cable.  Swapped around a bunch of stuff and it persisted.  I uninstalled the pkg (By triangle > delete on the installed app icon) then installed 0.65, it got stuck on the kingdom hearts music again, but didn't try to load db files.  It works fine on my slim ps3, not sure which cfw.  I'm using rebug dex because the bluray drive in this console doesn't work and I need a bluray emulator that has been made with an app and installed onto usb.

**Comment by bucanero** [comment]
do you have a working network connection? I suspect that your console is offline

the only action that happens after the music starts is the "auto update check", so I'm assuming that Apollo can't connect to the server and it keeps waiting for a response.

the auto-update check can be disabled from `Settings` but only after you start the app for the first time. 
(since you have another ps3, you could probably copy the Apollo settings save-file with disabled updates from the slim ps3 to the other console, and see if it works)

**Comment by dfgdgdgfd** [comment]
> do you have a working network connection? I suspect that your console is offline
> 
> the only action that happens after the music starts is the "auto update check", so I'm assuming that Apollo can't connect to the server and it keeps waiting for a response.
> 
> the auto-update check can be disabled from `Settings` but only after you start the app for the first time. (since you have another ps3, you could probably copy the Apollo settings save-file with disabled updates from the slim ps3 to the other console, and see if it works)

It's online but banned from psn, I imagine that won't affect your program though?  Where would the apollo settings file be on the slim ps3?

**Comment by dfgdgdgfd** [comment]
No luck, here's what I've tried:
copy apollo save from other ps3 without resigning (different user on other ps3)
copy but resign
Copy, resign, have internet connection
Have no apollo save but have internet connection

All result in black screen and 3 ps3 beeps when I eventually give up and hold down the power button.
