### ISSUE TITLE
My NHL 2K7 save files are corrupted

### ISSUE THREAD

**Issue by jlnhlfan** [bucanero/apollo-ps3#95]
I downloaded this program with the idea of finslly decrypting an NHL 2K7 roster file for use in RPCS3. I was trying to figure out which one was the roster, and when I finally attempted the decryption, I got an error, thanks to the game not being in the database.

Then, next thing you know, every file I load, save, or even CREATE in the game is corrupted! I'm never using this crappy PS3 malware ever again, because it corrupts game saves.

**Comment by Masamune3210** [comment]
This is not malware lol. Never operate on any files without a backup for situations exactly like this, things can go wrong no matter how well the program is made or how well you follow instructions.

**Comment by bucanero** [comment]
It's not clear if you're using Apollo on real hardware or on the RPCS3 emulator, but just in case:

**Apollo is developed, built, and tested only to be used on real PS3 hardware**. Any issues related to RPCS3 are out of scope.

Since you have time to complain, maybe you also have time to build a save-game decrypt tool yourself.
